-- Life Tracker v2 — 種目マスタ seed (一般的な種目一式)
-- Round 3 / S-DB-2 (2026-08-31)
-- 適用方法: Supabase MCP `apply_migration` (name: "v2_exercise_seed")
--
-- 方針:
--   - 一般的なジム種目を網羅的に投入する。使わない種目は削除せず is_archived = true で隠す
--     (workout_set からの参照先消失を防ぐため物理削除しない)
--   - sort_order は部位ごとに 100 番台単位。間に挿入できるよう番号を空けている
--   - ON CONFLICT DO NOTHING で再適用可能 (name に UNIQUE INDEX)

INSERT INTO exercise (name, muscle_group, equipment, metric_kind, sort_order) VALUES
-- ===== 胸 =====
('ベンチプレス',                     'chest','barbell',   'weight_reps',101),
('インクラインベンチプレス',         'chest','barbell',   'weight_reps',102),
('デクラインベンチプレス',           'chest','barbell',   'weight_reps',103),
('スミスマシンベンチプレス',         'chest','machine',   'weight_reps',104),
('ダンベルプレス',                   'chest','dumbbell',  'weight_reps',105),
('インクラインダンベルプレス',       'chest','dumbbell',  'weight_reps',106),
('デクラインダンベルプレス',         'chest','dumbbell',  'weight_reps',107),
('ダンベルフライ',                   'chest','dumbbell',  'weight_reps',108),
('インクラインダンベルフライ',       'chest','dumbbell',  'weight_reps',109),
('チェストプレス（マシン）',         'chest','machine',   'weight_reps',110),
('インクラインチェストプレス（マシン）','chest','machine', 'weight_reps',111),
('ペックフライ（マシン）',           'chest','machine',   'weight_reps',112),
('ケーブルクロスオーバー',           'chest','cable',     'weight_reps',113),
('ローケーブルフライ',               'chest','cable',     'weight_reps',114),
('ディップス（胸）',                 'chest','bodyweight','weight_reps',115),
('ダンベルプルオーバー',             'chest','dumbbell',  'weight_reps',116),
('プッシュアップ',                   'chest','bodyweight','reps_only', 117),
('ワイドプッシュアップ',             'chest','bodyweight','reps_only', 118),
('デクラインプッシュアップ',         'chest','bodyweight','reps_only', 119),
-- ===== 背中 =====
('デッドリフト',                     'back','barbell',    'weight_reps',201),
('ラックプル',                       'back','barbell',    'weight_reps',202),
('ベントオーバーロー',               'back','barbell',    'weight_reps',203),
('Tバーロー',                        'back','barbell',    'weight_reps',204),
('ペンドレイロー',                   'back','barbell',    'weight_reps',205),
('ワンハンドダンベルロー',           'back','dumbbell',   'weight_reps',206),
('ダンベルベントオーバーロー',       'back','dumbbell',   'weight_reps',207),
('ラットプルダウン',                 'back','machine',    'weight_reps',208),
('ラットプルダウン（パラレルグリップ）','back','machine',  'weight_reps',209),
('ビハインドネックプルダウン',       'back','machine',    'weight_reps',210),
('シーテッドロー（ケーブル）',       'back','machine',    'weight_reps',211),
('マシンロー',                       'back','machine',    'weight_reps',212),
('チンニング（順手懸垂）',           'back','bodyweight', 'weight_reps',213),
('チンアップ（逆手懸垂）',           'back','bodyweight', 'weight_reps',214),
('アシストチンニング（マシン）',     'back','machine',    'weight_reps',215),
('ストレートアームプルダウン',       'back','cable',      'weight_reps',216),
('ケーブルプルオーバー',             'back','cable',      'weight_reps',217),
('ハイパーエクステンション（マシン）','back','machine',   'weight_reps',218),
('インバーテッドロー（斜め懸垂）',   'back','bodyweight', 'reps_only', 219),
('バックエクステンション',           'back','bodyweight', 'reps_only', 220),
-- ===== 僧帽筋 =====
('バーベルシュラッグ',               'traps','barbell',   'weight_reps',251),
('ダンベルシュラッグ',               'traps','dumbbell',  'weight_reps',252),
('スミスマシンシュラッグ',           'traps','machine',   'weight_reps',253),
('ケーブルシュラッグ',               'traps','cable',     'weight_reps',254),
('アップライトロー',                 'traps','barbell',   'weight_reps',255),
-- ===== 肩 =====
('ショルダープレス（バーベル）',     'shoulders','barbell',   'weight_reps',301),
('ミリタリープレス',                 'shoulders','barbell',   'weight_reps',302),
('ショルダープレス（ダンベル）',     'shoulders','dumbbell',  'weight_reps',303),
('ショルダープレス（マシン）',       'shoulders','machine',   'weight_reps',304),
('アーノルドプレス',                 'shoulders','dumbbell',  'weight_reps',305),
('サイドレイズ',                     'shoulders','dumbbell',  'weight_reps',306),
('ケーブルサイドレイズ',             'shoulders','cable',     'weight_reps',307),
('マシンサイドレイズ',               'shoulders','machine',   'weight_reps',308),
('フロントレイズ',                   'shoulders','dumbbell',  'weight_reps',309),
('ケーブルフロントレイズ',           'shoulders','cable',     'weight_reps',310),
('リアレイズ',                       'shoulders','dumbbell',  'weight_reps',311),
('リアデルトフライ（マシン）',       'shoulders','machine',   'weight_reps',312),
('フェイスプル',                     'shoulders','cable',     'weight_reps',313),
('パイクプッシュアップ',             'shoulders','bodyweight','reps_only', 314),
('バンドプルアパート',               'shoulders','band',      'reps_only', 315),
-- ===== 上腕二頭 =====
('バーベルカール',                   'biceps','barbell', 'weight_reps',401),
('EZバーカール',                     'biceps','barbell', 'weight_reps',402),
('ドラッグカール',                   'biceps','barbell', 'weight_reps',403),
('ダンベルカール',                   'biceps','dumbbell','weight_reps',404),
('ハンマーカール',                   'biceps','dumbbell','weight_reps',405),
('インクラインダンベルカール',       'biceps','dumbbell','weight_reps',406),
('コンセントレーションカール',       'biceps','dumbbell','weight_reps',407),
('スパイダーカール',                 'biceps','dumbbell','weight_reps',408),
('プリーチャーカール（マシン）',     'biceps','machine', 'weight_reps',409),
('ケーブルカール',                   'biceps','cable',   'weight_reps',410),
-- ===== 上腕三頭 =====
('トライセプスプレスダウン',         'triceps','cable',     'weight_reps',501),
('ロープトライセプスプレスダウン',   'triceps','cable',     'weight_reps',502),
('ケーブルオーバーヘッドエクステンション','triceps','cable', 'weight_reps',503),
('ライイングトライセプスエクステンション','triceps','barbell','weight_reps',504),
('ナローグリップベンチプレス',       'triceps','barbell',   'weight_reps',505),
('オーバーヘッドトライセプスエクステンション','triceps','dumbbell','weight_reps',506),
('キックバック',                     'triceps','dumbbell',  'weight_reps',507),
('トライセプスマシン',               'triceps','machine',   'weight_reps',508),
('ディップス（三頭）',               'triceps','bodyweight','weight_reps',509),
('ベンチディップス',                 'triceps','bodyweight','reps_only', 510),
('ナロープッシュアップ',             'triceps','bodyweight','reps_only', 511),
-- ===== 前腕 =====
('リストカール',                     'forearms','dumbbell',  'weight_reps',601),
('リバースリストカール',             'forearms','dumbbell',  'weight_reps',602),
('リバースカール',                   'forearms','barbell',   'weight_reps',603),
('デッドハング',                     'forearms','bodyweight','duration',  604),
('ハンドグリップ',                   'forearms','other',     'reps_only', 605),
-- ===== 大腿四頭 =====
('バーベルスクワット',               'quads','barbell',   'weight_reps',701),
('フロントスクワット',               'quads','barbell',   'weight_reps',702),
('スミスマシンスクワット',           'quads','machine',   'weight_reps',703),
('レッグプレス',                     'quads','machine',   'weight_reps',704),
('ハックスクワット',                 'quads','machine',   'weight_reps',705),
('レッグエクステンション',           'quads','machine',   'weight_reps',706),
('ブルガリアンスクワット',           'quads','dumbbell',  'weight_reps',707),
('ダンベルランジ',                   'quads','dumbbell',  'weight_reps',708),
('ウォーキングランジ',               'quads','dumbbell',  'weight_reps',709),
('ゴブレットスクワット',             'quads','dumbbell',  'weight_reps',710),
('ステップアップ',                   'quads','dumbbell',  'weight_reps',711),
('自重スクワット',                   'quads','bodyweight','reps_only', 712),
('シシースクワット',                 'quads','bodyweight','reps_only', 713),
('ジャンピングスクワット',           'quads','bodyweight','reps_only', 714),
('ウォールシット',                   'quads','bodyweight','duration',  715),
-- ===== ハムストリング =====
('レッグカール（ライイング）',       'hamstrings','machine',   'weight_reps',801),
('レッグカール（シーテッド）',       'hamstrings','machine',   'weight_reps',802),
('ルーマニアンデッドリフト',         'hamstrings','barbell',   'weight_reps',803),
('スティフレッグデッドリフト',       'hamstrings','barbell',   'weight_reps',804),
('グッドモーニング',                 'hamstrings','barbell',   'weight_reps',805),
('ダンベルルーマニアンデッドリフト', 'hamstrings','dumbbell',  'weight_reps',806),
('ノルディックハムストリングカール', 'hamstrings','bodyweight','reps_only', 807),
('グルートハムレイズ',               'hamstrings','bodyweight','reps_only', 808),
-- ===== 臀部 =====
('ヒップスラスト',                   'glutes','barbell',   'weight_reps',851),
('ヒップスラスト（マシン）',         'glutes','machine',   'weight_reps',852),
('ヒップアブダクション（マシン）',   'glutes','machine',   'weight_reps',853),
('ヒップアダクション（マシン）',     'glutes','machine',   'weight_reps',854),
('バックキック（マシン）',           'glutes','machine',   'weight_reps',855),
('ケーブルキックバック',             'glutes','cable',     'weight_reps',856),
('グルートブリッジ',                 'glutes','bodyweight','reps_only', 857),
-- ===== ふくらはぎ =====
('スタンディングカーフレイズ',       'calves','machine',  'weight_reps',901),
('シーテッドカーフレイズ',           'calves','machine',  'weight_reps',902),
('レッグプレスカーフレイズ',         'calves','machine',  'weight_reps',903),
('ダンベルカーフレイズ',             'calves','dumbbell', 'weight_reps',904),
-- ===== 体幹 =====
('クランチ',                         'core','bodyweight','reps_only',1001),
('シットアップ',                     'core','bodyweight','reps_only',1002),
('バイシクルクランチ',               'core','bodyweight','reps_only',1003),
('レッグレイズ',                     'core','bodyweight','reps_only',1004),
('ハンギングレッグレイズ',           'core','bodyweight','reps_only',1005),
('ハンギングニーレイズ',             'core','bodyweight','reps_only',1006),
('Vシット',                          'core','bodyweight','reps_only',1007),
('デッドバグ',                       'core','bodyweight','reps_only',1008),
('バードドッグ',                     'core','bodyweight','reps_only',1009),
('アブローラー',                     'core','other',     'reps_only',1010),
('プランク',                         'core','bodyweight','duration', 1011),
('サイドプランク',                   'core','bodyweight','duration', 1012),
('ホローホールド',                   'core','bodyweight','duration', 1013),
('マウンテンクライマー',             'core','bodyweight','duration', 1014),
('ロシアンツイスト',                 'core','dumbbell',  'weight_reps',1015),
('ケーブルクランチ',                 'core','cable',     'weight_reps',1016),
('アブドミナルクランチ（マシン）',   'core','machine',   'weight_reps',1017),
('トーソローテーション（マシン）',   'core','machine',   'weight_reps',1018),
-- ===== 有酸素 =====
('トレッドミル（ランニング）',       'cardio','machine','duration_distance',1101),
('トレッドミル（ウォーキング）',     'cardio','machine','duration_distance',1102),
('エアロバイク',                     'cardio','machine','duration_distance',1103),
('リカンベントバイク',               'cardio','machine','duration_distance',1104),
('クロストレーナー',                 'cardio','machine','duration_distance',1105),
('ローイングマシン',                 'cardio','machine','duration_distance',1106),
('アサルトバイク',                   'cardio','machine','duration_distance',1107),
('ステアクライマー',                 'cardio','machine','duration',         1108),
('ランニング（屋外）',               'cardio','other',  'duration_distance',1109),
('ウォーキング（屋外）',             'cardio','other',  'duration_distance',1110),
('サイクリング（屋外）',             'cardio','other',  'duration_distance',1111),
('水泳',                             'cardio','other',  'duration_distance',1112),
('縄跳び',                           'cardio','other',  'duration',         1113),
-- ===== 全身 =====
('パワークリーン',                   'full_body','barbell',   'weight_reps',1201),
('クリーン&ジャーク',                'full_body','barbell',   'weight_reps',1202),
('スナッチ',                         'full_body','barbell',   'weight_reps',1203),
('スラスター',                       'full_body','barbell',   'weight_reps',1204),
('ケトルベルスイング',               'full_body','kettlebell','weight_reps',1205),
('ターキッシュゲットアップ',         'full_body','kettlebell','weight_reps',1206),
('バーピー',                         'full_body','bodyweight','reps_only', 1207),
('ボックスジャンプ',                 'full_body','bodyweight','reps_only', 1208),
('バトルロープ',                     'full_body','other',     'duration',  1209)
ON CONFLICT (name) DO NOTHING;
